theme                    : jekyll-theme-slate
locale                   : "ko-KR"
title                    : "GCGenome LIMS team tech blog"
title_separator          : "-"
name                     : "GCGenome LIMS"
description              : ""
url                      : ""
baseurl                  : "https://gcgenome-lims.github.io/"
theme: jekyll-theme-minimal