theme: minima
locale: ko-KR
timezone: Asia/Seoul
title: GCGenome LIMS Tech
email: sayaya@gccorp.com
description: ''
baseurl: ''
url: ''
twitter_username: ''
github_username: ''
plugins:
  - jekyll-feed
  - jekyll-paginate
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: '/page/:num/'